const SUPABASE_URL="https://wrczpnhesorptjzwdizd.supabase.co",SUPABASE_ANON_KEY="sb_publishable_cm8re92ds8XLhspfdNSwuw_X74b7kDm",MAX_SECONDS=90;
const supabaseClient=window.supabase?.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
let mediaRecorder,chunks=[],audioBlob,timerInterval,elapsedSeconds=0,stream;
const recordButton=document.getElementById("recordButton"),resetButton=document.getElementById("resetButton"),submitButton=document.getElementById("submitButton"),statusText=document.getElementById("statusText"),timerText=document.getElementById("timerText"),previewWrap=document.getElementById("previewWrap"),previewAudio=document.getElementById("previewAudio"),form=document.getElementById("submissionForm");
const setStatus=m=>statusText.textContent=m;
function setRecordingState(active){recordButton.textContent=active?"Stop Recording":"Start Recording";recordButton.setAttribute("aria-pressed",String(active));recordButton.setAttribute("aria-label",active?"Stop recording":"Start recording");recordButton.classList.toggle("is-recording",active);}
function updateTimer(){elapsedSeconds++;timerText.textContent=`${elapsedSeconds} ${elapsedSeconds===1?"second":"seconds"}`;if(elapsedSeconds>=MAX_SECONDS)stopRecording();}
function resetRecording(){clearInterval(timerInterval);stream?.getTracks().forEach(t=>t.stop());chunks=[];audioBlob=null;elapsedSeconds=0;timerText.textContent="0 seconds";previewAudio.removeAttribute("src");previewWrap.classList.add("hidden");submitButton.disabled=true;resetButton.disabled=true;setRecordingState(false);setStatus("Ready to record.");}
function preferredMimeType(){return["audio/mp4","audio/webm;codecs=opus","audio/webm","audio/ogg;codecs=opus","audio/ogg"].find(t=>window.MediaRecorder?.isTypeSupported?.(t))||"";}
async function startRecording(){try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setStatus("This browser does not support audio recording. Please try another browser.");return;}stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const type=preferredMimeType();mediaRecorder=type?new MediaRecorder(stream,{mimeType:type}):new MediaRecorder(stream);chunks=[];mediaRecorder.addEventListener("dataavailable",e=>{if(e.data?.size)chunks.push(e.data)});mediaRecorder.addEventListener("stop",()=>{audioBlob=new Blob(chunks,{type:mediaRecorder.mimeType||"audio/webm"});previewAudio.src=URL.createObjectURL(audioBlob);previewWrap.classList.remove("hidden");submitButton.disabled=false;resetButton.disabled=false;stream?.getTracks().forEach(t=>t.stop());setRecordingState(false);setStatus("Recording stopped. Your preview is ready. You can listen, reset, or submit it.");recordButton.focus()},{once:true});mediaRecorder.start(1000);submitButton.disabled=true;resetButton.disabled=true;elapsedSeconds=0;timerText.textContent="0 seconds";setRecordingState(true);setStatus("Recording started. Press the same Stop Recording button when finished.");clearInterval(timerInterval);timerInterval=setInterval(updateTimer,1000)}catch(e){console.error(e);setRecordingState(false);setStatus("Microphone access failed. Please allow microphone permission and try again.");recordButton.focus();}}
function stopRecording(){clearInterval(timerInterval);if(mediaRecorder?.state==="recording"){mediaRecorder.requestData();mediaRecorder.stop()}else setRecordingState(false);}
function toggleRecording(){mediaRecorder?.state==="recording"?stopRecording():startRecording();}
async function submitRecording(e){e.preventDefault();if(!audioBlob){setStatus("Please record a message before submitting.");return}if(!supabaseClient){setStatus("Supabase is not configured yet.");return}submitButton.disabled=true;setStatus("Uploading your message for review.");const name=document.getElementById("speakerName").value.trim(),email=document.getElementById("speakerEmail").value.trim(),title=document.getElementById("messageTitle").value.trim(),anonymous=document.getElementById("anonymous").checked,ext=audioBlob.type.includes("mp4")?"m4a":audioBlob.type.includes("webm")?"webm":"ogg",path=`pending/${crypto.randomUUID()}.${ext}`;const{error:uploadError}=await supabaseClient.storage.from("encouragement-audio").upload(path,audioBlob,{contentType:audioBlob.type,upsert:false});if(uploadError){setStatus("Upload failed. Please try again.");submitButton.disabled=false;return}const{data:url}=supabaseClient.storage.from("encouragement-audio").getPublicUrl(path);const{error:insertError}=await supabaseClient.from("submissions").insert({speaker_name:name||null,speaker_email:email||null,anonymous,title:title||"Encouragement Message",original_audio_url:url.publicUrl,status:"pending",share_slug:crypto.randomUUID().slice(0,12)});if(insertError){setStatus("Your audio uploaded, but the submission record failed. Please contact the administrator.");submitButton.disabled=false;return}form.reset();resetRecording();setStatus("Submission received. Thank you for sharing encouragement.");}
recordButton.addEventListener("click",toggleRecording);resetButton.addEventListener("click",resetRecording);form.addEventListener("submit",submitRecording);