'use strict';
const $=id=>document.getElementById(id);
let session={},selected=null,recognition=null,controller=null,busy=false,embedded=false, spotifyController=null, spotifyActive=false, spotifyState="Ready";
const approvedHosts=new Set(['eventhoughimblind.com','eventhoughimblind.wordpress.com','cazernybussey.github.io','zeno.fm','stream.zeno.fm','open.spotify.com','p.scdn.co','podcasts.apple.com','anchor.fm','podcasters.spotify.com','creators.spotify.com','donorbox.org','form.jotform.com','www.facebook.com','www.instagram.com','youtube.com','www.youtube.com','www.tiktok.com','twitter.com','x.com','www.linkedin.com','www.threads.net','www.threads.com','cazernybussey.substack.com','flickr.com','calendly.com','eventhoughimblind.us22.list-manage.com','cfly-ai.zapier.app','eventhoughimblind.zapier.app','elevenlabs.io','www.imperfektlymade.com','eyeslikemine.org','etib-community-connect-1.onrender.com','eepurl.com','a.co','music.amazon.com','www.iheart.com','wrczpnhesorptjzwdizd.supabase.co']);
function safeURL(value,media=false){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&(!u.port||u.port==='443')&&(approvedHosts.has(u.hostname)||(media&&(u.hostname.endsWith('.cloudfront.net')||u.hostname.endsWith('.spotify.com')||u.hostname.endsWith('.scdn.co'))))?u.href:null}catch{return null}}
function status(text){$('status').textContent=text}
function silence(){if('speechSynthesis'in window)window.speechSynthesis.cancel()}
function read(text){if(!$('read-aloud').checked||!('speechSynthesis'in window)||!$('audio').paused)return;silence();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='en-US';window.speechSynthesis.speak(utterance)}
function addHistory(who,text){const li=document.createElement('li');const strong=document.createElement('strong');strong.textContent=who+': ';li.append(strong,document.createTextNode(text));$('history').append(li);while($('history').children.length>30)$('history').firstElementChild.remove()}
function link(url,label){const a=document.createElement('a');a.href=safeURL(url);a.textContent=label;return a}
function resultCard(item){const card=document.createElement('article');card.className='result';const h=document.createElement('h3');h.textContent=item.title;card.append(h);if(item.date){const p=document.createElement('p');p.className='date';const date=new Date(item.date.length===10?item.date+'T12:00:00':item.date);p.textContent=Number.isNaN(date.getTime())?item.date:date.toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric',timeZone:'America/New_York'});card.append(p)}if(item.description){const p=document.createElement('p');p.textContent=item.description.slice(0,700);card.append(p)}if(safeURL(item.url))card.append(link(item.url,item.preview?'Listen to the full episode on Spotify':'Open '+item.title));if(item.media&&safeURL(item.media,true)){const button=document.createElement('button');button.type='button';button.textContent=(item.preview?'Play preview: ':'Play: ')+item.title;button.addEventListener('click',()=>load(item));card.append(document.createElement('br'),button)}return card}
async function play(){if(spotifyActive){silence();$('media-status').textContent='Activate Play inside the Spotify player to start or resume this episode.';$('spotify-player').querySelector('iframe')?.focus();return}if(!selected){status('Choose audio first.');return}$('audio').hidden=false;silence();const target=selected;try{await Promise.race([$('audio').play(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Playback timeout')),12000))])}catch(e){if(selected!==target||e.name==='AbortError')return;$('media-status').textContent='Playback needs your permission or the source is unavailable. Activate Play selected audio, or open the media’s official page.';$('play').focus()}}
function pause(){silence();if(spotifyActive){$('media-status').textContent='Use Pause inside the Spotify player.';$('spotify-player').querySelector('iframe')?.focus();return}if(selected){$('audio').pause();$('media-status').textContent='Paused: '+selected.title}else status('No audio is selected.')}
function stop(){silence();if(spotifyActive){spotifyController?.destroy();spotifyController=null;spotifyActive=false;spotifyState='Stopped';$('spotify-player').replaceChildren(Object.assign(document.createElement('div'),{id:'spotify-mount'}));$('spotify-player').hidden=true;$('audio').hidden=false;}$('audio').pause();if(selected){$('audio').removeAttribute('src');$('audio').load();$('audio').hidden=true;$('play').hidden=false;$('pause').hidden=false;$('media-status').textContent='Stopped: '+selected.title}}
async function load(item){if(spotifyActive)stop();const url=safeURL(item.media,true);if(!url){status('This source cannot play here. Open its official page.');return}if(recognition){try{recognition.abort()}catch{}}silence();$('audio').pause();selected=item;session.playing_id=item.id;session.last_id=item.id;$('player').hidden=false;$('track').textContent=item.title+(item.preview?' — Spotify preview':'');$('track-link').href=safeURL(item.url);$('audio').hidden=false;$('play').hidden=false;$('pause').hidden=false;$('audio').src=url;$('media-status').textContent='Loading: '+$('track').textContent;void play()}
function navigate(url){url=safeURL(url);if(!url){status('This destination is not approved.');return}stop();if(embedded){window.parent.postMessage({type:'etib:navigate',url},parentOrigin);status('Opening the requested destination.')}else location.assign(url)}
async function send(message){if(busy)return;message=message.trim();if(!message)return;busy=true;controller=new AbortController();const timer=setTimeout(()=>controller?.abort(),45000);$('send').disabled=true;$('cancel-request').hidden=false;$('error').textContent='';$('response').setAttribute('aria-busy','true');status('Finding your ETIB answer…');addHistory('You',message);silence();
try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,session}),signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error||'This request could not be completed.');session=data.session||{};$('answer').textContent=data.text;$('results').replaceChildren(...(data.results||[]).map(resultCard));$('response').hidden=false;addHistory('ETIB',data.text);$('response-heading').focus();status('Response ready.');read(data.text);const a=data.action;if(a?.type==='play')await load(a.item);if(a?.type==='spotify')spotify(a.item);if(a?.type==='pause')pause();if(a?.type==='resume'){if(selected?.provider==='spotify'&&!spotifyActive){spotify(selected)}else{if(selected&&!$('audio').getAttribute('src'))$('audio').src=selected.media;void play()}}if(a?.type==='stop')stop();if(a?.type==='identify'){$('answer').textContent=selected?spotifyActive?'Selected in Spotify: '+selected.title+'. Playback is controlled inside the Spotify player.':($('audio').getAttribute('src')?$('audio').ended?'Finished: ':$('audio').paused?'Paused: ':'Playing: ':'Stopped: ')+selected.title+(selected.preview?' — preview':''):'Nothing is playing.';read($('answer').textContent)}if(a?.type==='navigate')navigate(a.url);
}catch(e){$('error').textContent=e.name==='AbortError'?'Request canceled or timed out. You can send it again.':'Could not retrieve an answer. '+e.message;status('Ready to try again.');$('question').focus()}finally{clearTimeout(timer);busy=false;controller=null;$('send').disabled=false;$('cancel-request').hidden=true;$('response').removeAttribute('aria-busy')}}
$('ask').addEventListener('submit',e=>{e.preventDefault();send($('question').value)});document.querySelectorAll('[data-question]').forEach(b=>b.addEventListener('click',()=>{$('question').value=b.dataset.question;send(b.dataset.question)}));$('cancel-request').addEventListener('click',()=>controller?.abort());$('play').addEventListener('click',()=>{if(selected?.provider==='spotify'&&!spotifyActive){spotify(selected);return}if(selected&&!$('audio').getAttribute('src'))$('audio').src=selected.media;play()});$('pause').addEventListener('click',pause);$('stop').addEventListener('click',stop);$('silence').addEventListener('click',silence);$('read-aloud').addEventListener('change',()=>{if(!$('read-aloud').checked)silence()});$('clear').addEventListener('click',()=>{controller?.abort();stop();session={};selected=null;$('history').replaceChildren();$('results').replaceChildren();$('answer').textContent='';$('response').hidden=true;$('player').hidden=true;status('Conversation cleared.');$('question').focus()});
$('audio').addEventListener('playing',()=>{$('media-status').textContent='Playing: '+$('track').textContent});$('audio').addEventListener('pause',()=>{if(selected&&!$('audio').ended&&$('audio').getAttribute('src'))$('media-status').textContent='Paused: '+$('track').textContent});$('audio').addEventListener('ended',()=>{$('media-status').textContent='Finished: '+$('track').textContent});$('audio').addEventListener('error',()=>{if(selected&&$('audio').getAttribute('src')){$('media-status').textContent='Audio could not be loaded. Try Play selected audio or open the official media page.'}});
const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;
if(Speech){recognition=new Speech();recognition.lang='en-US';recognition.interimResults=false;recognition.continuous=false;recognition.onstart=()=>{$('speak').textContent='Stop listening';$('speak').setAttribute('aria-pressed','true');status('Listening. Speak your request.');};recognition.onend=()=>{$('speak').textContent='Speak';$('speak').setAttribute('aria-pressed','false');};recognition.onresult=e=>{$('question').value=e.results[0][0].transcript;send($('question').value)};recognition.onerror=e=>{status(e.error==='not-allowed'?'Microphone permission was denied. Type your request or use keyboard dictation.':'Speech was unavailable. Type your request or try again.');$('question').focus()};$('speak').addEventListener('click',()=>{if($('speak').getAttribute('aria-pressed')==='true'){recognition.stop();status('Listening stopped.');return}silence();if(selected&&(!$('audio').paused||spotifyActive))pause();try{recognition.start()}catch{status('Speech is unavailable. Type your request.');$('question').focus()}})}else{$('speak').textContent='Voice input help';$('speak').addEventListener('click',()=>{status('This browser does not provide speech recognition. Use the dictation button on your device keyboard, or type your request.');$('question').focus()})}
if(!('speechSynthesis'in window)){$('read-aloud').disabled=true;$('silence').hidden=true}
const allowedParents=new Set([location.origin,'https://eventhoughimblind.com','https://eventhoughimblind.wordpress.com']);
window.addEventListener('message',e=>{if(!allowedParents.has(e.origin)||e.source!==window.parent)return;if(e.data?.type==='etib:initialize'){embedded=true;parentOrigin=e.origin;$('close').hidden=false;$('question').focus()}if(e.data?.type==='etib:stop'){stop();recognition?.abort()}});
let parentOrigin=location.origin;
$('close').addEventListener('click',()=>{stop();silence();window.parent.postMessage({type:'etib:close'},parentOrigin)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&embedded){e.preventDefault();$('close').click()}});
if(window.parent!==window)window.parent.postMessage({type:'etib:ready'},new URL(document.referrer||location.href).origin);
window.addEventListener('pagehide',()=>{stop();silence();recognition?.abort();$('audio').pause()});

function spotify(item){
 const url=safeURL(item.url);if(!url||!/^https:\/\/open\.spotify\.com\/episode\/[A-Za-z0-9]+$/.test(url)){status('Use the official episode link to listen.');return}
 stop();selected={...item,provider:'spotify',preview:false};session.playing_id=item.id;session.last_id=item.id;spotifyActive=true;spotifyState='Selected in Spotify';$('play').hidden=true;$('pause').hidden=true;$('player').hidden=false;$('audio').hidden=true;$('track').textContent=item.title+' — Spotify player';$('track-link').href=url;$('spotify-player').hidden=false;$('media-status').textContent='Use Play inside the Spotify player. Spotify may provide only a preview here. The full episode link is above.';
 const frame=document.createElement('iframe');frame.src='https://open.spotify.com/embed/episode/'+new URL(url).pathname.split('/').pop();frame.title='Spotify player: '+item.title;frame.width='100%';frame.height='232';frame.setAttribute('allow','autoplay; encrypted-media');frame.addEventListener('load',()=>{if(spotifyActive)frame.focus()});$('spotify-player').replaceChildren(frame);
}
