'use strict';
// Add a launcher button early in the document; point data-etib-url at this app's URL.
(()=>{const script=document.currentScript;const appURL=new URL(script.src);const appOrigin=appURL.origin;const launchers=document.querySelectorAll('[data-etib-launcher]');
launchers.forEach(button=>{const dialog=document.createElement('dialog');dialog.setAttribute('aria-labelledby','etib-dialog-heading');dialog.style.cssText='box-sizing:border-box;width:min(960px,100vw);height:92dvh;max-width:100vw;max-height:100dvh;margin:auto;padding:0;background:#071426;color:white;border:2px solid #f5c94a;border-radius:12px';const top=document.createElement('div');top.style.cssText='display:flex;gap:1rem;align-items:center;justify-content:space-between;padding:12px 16px';const heading=document.createElement('h2');heading.id='etib-dialog-heading';heading.textContent='Talk to ETIB';heading.style.cssText='margin:0;font:600 20px system-ui';const close=document.createElement('button');close.type='button';close.textContent='Close Talk to ETIB';close.style.cssText='font:16px system-ui;min-height:48px;padding:8px 16px;border:2px solid #f5c94a;background:#203955;color:white;border-radius:8px';const frame=document.createElement('iframe');frame.title='Talk to ETIB conversation';frame.allow='microphone';frame.src=appOrigin+'/';frame.style.cssText='display:block;border:0;width:100%;height:calc(100% - 76px)';top.append(heading,close);dialog.append(top,frame);document.body.append(dialog);let previous;
function shut(){frame.contentWindow.postMessage({type:'etib:stop'},appOrigin);dialog.close();(previous||button).focus()}
close.addEventListener('click',shut);dialog.addEventListener('cancel',e=>{e.preventDefault();shut()});button.addEventListener('click',()=>{previous=document.activeElement;dialog.showModal();close.focus();frame.contentWindow.postMessage({type:'etib:initialize'},appOrigin)});
window.addEventListener('message',e=>{if(e.origin!==appOrigin||e.source!==frame.contentWindow||!dialog.open)return;if(e.data?.type==='etib:ready')frame.contentWindow.postMessage({type:'etib:initialize'},appOrigin);if(e.data?.type==='etib:close')shut();if(e.data?.type==='etib:navigate'){// The child validates against the approved registry; validate again using server-maintained registry.
const url=e.data.url;fetch(appOrigin+'/api/registry').then(r=>r.json()).then(reg=>{const requested=new URL(url);const allowed=reg.some(x=>new URL(x.url).href===requested.href)||requested.origin==='https://eventhoughimblind.com'||(requested.origin==='https://open.spotify.com'&&requested.pathname.startsWith('/episode/'))||(requested.origin==='https://podcasters.spotify.com'&&requested.pathname.startsWith('/pod/show/'));if(requested.protocol==='https:'&&!requested.username&&!requested.password&&allowed){shut();location.assign(requested.href)}else close.focus()}).catch(()=>{const p=document.createElement('p');p.textContent='Open the requested link directly inside the conversation.';top.append(p)})}});
});})();
